version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build tasks..."

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

artifacts:
  files:
    - '**/*'
  # discard-paths: yes
  base-directory: 'build'
